[0m20:10:49.610362 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053ca050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053f9a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053fa110>]}


============================== 20:10:49.629450 | 4bcdba29-1f6a-4622-8182-ea67792285ba ==============================
[0m20:10:49.629450 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:10:49.630239 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/mikoto/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init my_project', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:10:49.730814 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'PosixPath'.. Dictionary: {'dir': PosixPath('/Users/mikoto/.dbt')}
[0m20:10:49.735229 [info ] [MainThread]: Creating dbt configuration folder at 
[0m20:10:49.738044 [debug] [MainThread]: Starter project path: /Users/mikoto/Documents/markitdown/myenv/lib/python3.11/site-packages/dbt/include/starter_project
[0m20:10:49.773958 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m20:10:49.775330 [info ] [MainThread]: Setting up your profile.
[0m20:10:49.776760 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m20:10:50.132239 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.87093586, "process_in_blocks": "0", "process_kernel_time": 0.322134, "process_mem_max_rss": "100941824", "process_out_blocks": "0", "process_user_time": 1.394124}
[0m20:10:50.133309 [debug] [MainThread]: Command `dbt init` failed at 20:10:50.133118 after 0.87 seconds
[0m20:10:50.133814 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102a99650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1012226d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105374450>]}
[0m20:10:50.134314 [debug] [MainThread]: Flushing usage events
[0m20:10:51.000713 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:11:21.058205 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102c5f690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054754d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054f6ad0>]}


============================== 20:11:21.066644 | 632c56b9-09f1-4172-a931-41b4ff6095aa ==============================
[0m20:11:21.066644 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:11:21.068936 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/mikoto/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt docs generate', 'send_anonymous_usage_stats': 'True'}
[0m20:11:21.070019 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/mikoto/Documents/markitdown/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:11:21.075064 [debug] [MainThread]: Resource report: {"command_name": "generate", "command_success": false, "command_wall_clock_time": 0.20973554, "process_in_blocks": "0", "process_kernel_time": 0.300566, "process_mem_max_rss": "100237312", "process_out_blocks": "0", "process_user_time": 1.279919}
[0m20:11:21.076346 [debug] [MainThread]: Command `dbt docs generate` failed at 20:11:21.076155 after 0.21 seconds
[0m20:11:21.076892 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105384550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105473fd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105473ed0>]}
[0m20:11:21.082238 [debug] [MainThread]: Flushing usage events
[0m20:11:21.908984 [debug] [MainThread]: An error was encountered while trying to flush usage events
